language: python

python:
  - "2.7"
  - "3.6"

install:
  -  pip install requests nose nose-cov python-coveralls
  -  pip install aliyun-python-sdk-sts

script:
  - nosetests test/ --with-cov

after_success:
  - coveralls
